# Generated by Django 5.1 on 2025-10-07 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pelicula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('fecha_lanzamiento', models.DateField()),
                ('genero', models.CharField(max_length=100)),
                ('duracion', models.IntegerField(help_text='Duración en minutos')),
                ('director', models.CharField(max_length=100)),
                ('reparto', models.TextField(help_text='Lista de actores principales')),
                ('clasificacion', models.CharField(help_text='Clasificación por edades', max_length=10)),
                ('idioma', models.CharField(max_length=50)),
                ('subtitulos', models.BooleanField(default=False)),
                ('url_trailer', models.URLField(blank=True, null=True)),
            ],
        ),
    ]

